name: debian_package

on:
  push:
    branches:
      - 'master'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'packages' output variable
      folders: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          nwchem-700.fedora.sockets: 'nwchem-700.fedora.sockets/*'
          nwchem-700.mpipr: 'nwchem-700.mpipr/*'
          builddebs.buster: 'builddebs.buster/*'
  docker:
    needs: changes
    strategy:
        matrix:
          folder: ${{ fromJSON(needs.changes.outputs.folders) }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: ${{ matrix.folder }}
          tags: user/app:latest
