name: nwchem_docker

on:
  push:
  pull_request:
  release:
  schedule:
    - cron: '0 0 * * SUN'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'folders' output variable
      folders: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          nwchem-700.fedora.sockets: 'nwchem-700.fedora.sockets/*'
          nwchem-700.mpipr: 'nwchem-700.mpipr/*'
          nwchem-700.amazonlinux.sockets: 'nwchem-700.amazonlinux.sockets/*'
          nwchem-dev: 'nwchem-dev/*'
          nwchem-dev.qc: 'nwchem-dev.qc/*'
          builddebs.buster: 'builddebs.buster/*'
  docker:
    needs: changes
    strategy:
        matrix:
          folder: ${{ fromJSON(needs.changes.outputs.folders) }}
    runs-on: ubuntu-latest
    steps:
      -
        if: ${{ github.actor == 'nwchemgit' }}
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.actor == 'nwchemgit' }}
          context: ${{ matrix.folder }}
          tags: ghcr.io/${{ github.actor }}/${{ matrix.folder }}:latest
